auto_learn_enabled: false
available_domains:
- general
- shop
- tech
- personal
colorize_output: true
confidence_threshold: 0.7
conversation_cleanup_days: 30
database_path: data/knowledge.db
default_domain: general
enable_conversation_logging: true
energy_threshold: 300
log_file: logs/chatbot.log
log_level: INFO
max_context_length: 5
max_knowledge_entries: 10000
max_response_length: 500
min_confidence_for_auto_learn: 0.9
pause_threshold: 0.8
phrase_time_limit: 10
sentence_model_name: all-MiniLM-L6-v2
show_confidence_scores: false
speech_rate: 150
timeout: 5
tts_language: hi
use_gtts: true
voice_enabled: true
voice_id: 0
voice_language: hi-IN
